// ===========================================================
// Recetas de repostería / pan, tomadas del Excel
// "Italo_Recetas_MEC3.xlsx" (hoja por receta).
// La cantidad base = columna "1 mezcla". La app escala a 2, 4, 5…
// con el escalador de porciones (unidad = "mezcla").
// Se omitió la hoja "Masa Frolla NO USAR".
// ===========================================================
import { receta, ing, ingAg } from './seed-helpers'
import {
  COVER_TORTA, COVER_BROWNIE, COVER_MUFFIN, COVER_CREMA,
  COVER_PIE, COVER_MASA, COVER_MERENGUE,
} from './covers'

const M = (data) => receta(data.id, { categoria: 'pan', rendimiento: 1, unidadRendimiento: 'mezcla', ...data })

export const RECETAS_PAN = [
  M({
    id: 'base_pan_torta_vainilla',
    nombre: 'Torta de Vainilla',
    cover: COVER_TORTA,
    ingredientes: [
      ing('Harina', 300, 'g'),
      ing('Azúcar blanca', 300, 'g'),
      ing('Huevos (≈4 und)', 250, 'g'),
      ing('Leche', 250, 'g'),
      ing('Mantequilla', 115, 'g'),
      ing('Polvo de hornear', 10, 'g'),
      ing('French vanilla', 10, 'g'),
      ing('Aceite (a la leche caliente)', 12, 'g'),
      ing('Sal', 2, 'g'),
    ],
    pasos: [
      'Batir el azúcar con los huevos hasta triplicar el volumen.',
      'En un bowl aparte poner la harina, la sal y el polvo de hornear; agregarlos a la mezcla de huevos en 3 partes, batiendo apenas para integrar.',
      'Calentar la leche y derretir en ella la mantequilla y el aceite.',
      'Agregar una porción (100 g) de la mezcla a la leche caliente, mezclar, y luego incorporar esa leche al resto de la mezcla.',
    ],
  }),
  M({
    id: 'base_pan_torta_chocolate',
    nombre: 'Torta de Chocolate',
    cover: COVER_TORTA,
    ingredientes: [
      ing('Harina', 350, 'g'),
      ing('Leche', 375, 'g'),
      ing('Azúcar morena', 250, 'g'),
      ing('Huevos', 110, 'g'),
      ing('Azúcar blanca', 100, 'g'),
      ing('Aceite', 98, 'g'),
      ing('Cacao Giuso', 40, 'g'),
      ing('Limón', 20, 'g'),
      ing('French vanilla MEC3', 10, 'g'),
      ing('Bicarbonato', 8, 'g'),
      ing('Sal', 1, 'g'),
    ],
    pasos: [
      'Batir el aceite con el azúcar morena y el azúcar blanca.',
      'Agregar los huevos uno a uno, dejando que emulsione.',
      'Calentar la leche y agregar el limón (se corta).',
      'Incorporar a la mezcla intercalando con los polvos cernidos (harina, cacao, bicarbonato y sal) y la French vanilla.',
      'Hornear a 150°C: torta grande 30 min; cupcakes 20 min.',
    ],
    notas: 'Molde de torta de 15 cm de diámetro: 1000 g por molde. Cupcake grande: 100 g. ⚠️ La hoja original solo traía los datos de horneado; el método de mezclado se adaptó de la Torta de Banano (es muy parecida). Verifícalo con tu preparación.',
  }),
  M({
    id: 'base_pan_torta_zanahoria',
    nombre: 'Torta de Zanahoria',
    cover: COVER_TORTA,
    ingredientes: [
      ing('Harina', 600, 'g'),
      ing('Azúcar morena', 585, 'g'),
      ing('Aceite', 405, 'g'),
      ing('Huevos (≈6 und)', 330, 'g'),
      ing('Zanahoria rallada', 315, 'g'),
      ing('Polvo de hornear', 23, 'g'),
      ing('Canela', 15, 'g'),
      ing('French vanilla', 15, 'g'),
      ing('Nuez moscada', 9, 'g'),
      ing('Sal', 8, 'g'),
    ],
    pasos: [
      'Batir los huevos con el azúcar.',
      'Agregar el aceite poco a poco junto con la French vanilla.',
      'Agregar los polvos juntos (harina, polvo de hornear, canela, nuez moscada y sal).',
      'Agregar la zanahoria rallada.',
    ],
  }),
  M({
    id: 'base_pan_torta_banano',
    nombre: 'Torta de Banano',
    cover: COVER_TORTA,
    ingredientes: [
      ing('Bananos', 600, 'g'),
      ing('Harina', 580, 'g'),
      ing('Azúcar morena', 400, 'g'),
      ing('Huevos', 250, 'g'),
      ing('Aceite', 190, 'g'),
      ing('Leche', 60, 'g'),
      ing('Polvo de hornear', 33, 'g'),
      ing('Vinagre', 20, 'g'),
      ing('French vanilla MEC3', 10, 'g'),
    ],
    pasos: [
      'Batir el aceite con el azúcar morena 5 minutos con el escudo.',
      'Agregar los huevos uno a uno, dejando que emulsione.',
      'Calentar la leche y agregar el vinagre; incorporar a la mezcla intercalando con los polvos (harina y polvo de hornear).',
      'Agregar el banano aplastado.',
    ],
    notas: 'El polvo de hornear (33 g) tiene una anotación alterna de "Sal 2 g" en la hoja original.',
  }),
  M({
    id: 'base_pan_brownies',
    nombre: 'Brownies',
    cover: COVER_BROWNIE,
    ingredientes: [
      ing('Azúcar blanca', 1000, 'g'),
      ing('Margarina', 500, 'g'),
      ing('Chocolate semi amargo', 400, 'g'),
      ing('Harina', 400, 'g'),
      ing('Cacao Giuso', 100, 'g'),
      ing('Huevos', 10, 'unidad'),
    ],
    pasos: [
      'Precalentar el horno a 150°C (hornear 30 min).',
      'Mezclar el azúcar con los huevos y batir 20 minutos con el globo.',
      'Aparte, derretir la margarina con el chocolate.',
      'Aparte, cernir la harina con el cacao.',
      'Mezclar todo a los huevos intercalando el chocolate y los polvos.',
    ],
    notas: 'Rinde 1 bandeja. Los huevos figuran como "10" en la hoja original; se interpretan como 10 unidades. Verifica con la receta física.',
  }),
  M({
    id: 'base_pan_muffins_coco',
    nombre: 'Muffins de Coco',
    cover: COVER_MUFFIN,
    ingredientes: [
      ing('Huevos', 290, 'g'),
      ing('Azúcar en polvo', 270, 'g'),
      ing('Harina', 270, 'g'),
      ing('Mantequilla', 180, 'g'),
      ing('Agua', 160, 'g'),
      ing('Coco super premium', 120, 'g'),
      ing('Miel', 10, 'g'),
      ing('Polvo de hornear', 10, 'g'),
      ing('Sal', 2, 'g'),
    ],
    pasos: [
      'En una olla: agua, miel, sal y mantequilla.',
      'Cuando derritan, agregar la harina y mezclar por 7 minutos.',
      'Pasar a la batidora con el escudo.',
    ],
    notas: 'La hoja original detalla hasta este punto. Luego incorpora en la batidora los huevos, el azúcar en polvo, el coco y el polvo de hornear según la práctica de Italo.',
  }),
  M({
    id: 'base_pan_masa_frolla',
    nombre: 'Masa Frolla #2',
    cover: COVER_MASA,
    ingredientes: [
      ing('Harina de pizza', 500, 'g'),
      ing('Mantequilla', 150, 'g'),
      ing('Azúcar en polvo', 150, 'g'),
      ing('Huevos', 110, 'g'),
      ing('Margarina', 100, 'g'),
    ],
    pasos: [
      'Mezclar el azúcar con la harina tamizada.',
      'La mantequilla debe estar suave: ponerla en el centro de los polvos y hacer migas.',
      'Agregar los huevos y amasar.',
      'Hornear 10 min a 160°C con frijoles (horneado ciego / peso ciego).',
      'Quitar los frijoles, poner el relleno y hornear 12 min más.',
    ],
    notas: 'Esta es la Masa Frolla #2 (la marcada "Sí usar" en el documento).',
  }),
  M({
    id: 'base_pan_pie_limon',
    nombre: 'Pie de Limón (relleno)',
    cover: COVER_PIE,
    ingredientes: [
      ing('Leche condensada', 794, 'g'),
      ing('Jugo de limón', 180, 'g'),
      ing('Yemas de huevo', 4, 'unidad'),
    ],
    pasos: [
      'Mezclar todos los ingredientes y poner en una olla a cocinar a fuego lento hasta que espese.',
      'Poner sobre la tartaleta vacía, previamente cocida por 18 minutos a 160°C.',
    ],
  }),
  M({
    id: 'base_pan_crema_pastelera',
    nombre: 'Crema Pastelera',
    cover: COVER_CREMA,
    ingredientes: [
      ing('Leche', 500, 'g'),
      ing('Azúcar', 130, 'g'),
      ing('Yemas', 125, 'g'),
      ing('Almidón (maicena)', 40, 'g'),
      ingAg('French vanilla'),
    ],
    pasos: [
      'Poner a calentar la leche en una olla.',
      'Aparte poner las yemas con el azúcar y el almidón.',
      'Cuando la leche hierva, sacar un poco encima de las yemas, mezclar y devolver todo a la olla pasando por un colador.',
      'Mezclar hasta espesar.',
    ],
    notas: 'La cantidad de French vanilla no estaba especificada en la hoja original (agregar al gusto).',
  }),
  M({
    id: 'base_pan_glaseado_queso',
    nombre: 'Glaseado de Queso Crema',
    cover: COVER_CREMA,
    ingredientes: [
      ing('Queso crema', 480, 'g'),
      ing('Azúcar en polvo', 360, 'g'),
      ing('Mantequilla sin sal', 180, 'g'),
      ing('Base Quark MEC3', 30, 'g'),
      ing('Leche', 30, 'g'),
      ing('Ralladura de limón', 2, 'g'),
    ],
    pasos: [
      'Cernir el azúcar en polvo.',
      'Batir la mantequilla con el queso crema.',
      'Una vez batido y cremoso, agregar poco a poco el azúcar.',
      'Agregar el sabor (ralladura de limón) después de batir.',
    ],
  }),
  M({
    id: 'base_pan_crema_ruby',
    nombre: 'Crema de Quella Ruby',
    cover: COVER_CREMA,
    ingredientes: [
      ing('Quella Ruby', 420, 'g'),
      ing('Crema de leche', 315, 'g'),
      ing('Chocolate blanco', 220, 'g'),
      ing('Mantequilla', 57, 'g'),
      ing('Agua', 10, 'g'),
      ing('Gelatina sin sabor', 3, 'g'),
    ],
    pasos: [
      'Hidratar la gelatina sin sabor en el agua.',
      'Aparte, calentar la crema y cuando esté caliente agregar el chocolate blanco; mezclar bien.',
      'Agregar la gelatina disuelta.',
      'Agregar la Quella Ruby y mezclar con mixer.',
      'Agregar la mantequilla a los 40°C y emulsionar.',
      'Dejar reposar un día en frío y luego batir en la batidora con el escudo.',
    ],
  }),
  M({
    id: 'base_pan_crema_morettina',
    nombre: 'Crema de Quella Morettina',
    cover: COVER_CREMA,
    ingredientes: [
      ing('Morettina pepita', 403, 'g'),
      ing('Crema de leche', 313, 'g'),
      ing('Chocolate Belcolade', 200, 'g'),
      ing('Mantequilla', 56, 'g'),
      ing('Agua', 10, 'g'),
      ing('Gelatina sin sabor', 3, 'g'),
    ],
    pasos: [
      'Hidratar la gelatina en el agua.',
      'Poner a hervir la crema y ponerla sobre el chocolate Belcolade.',
      'Mezclar la gelatina y la Morettina.',
      'Emulsionar la mantequilla usando un mixer.',
      'Dejar reposar un día y luego batir usando el escudo.',
    ],
  }),
  M({
    id: 'base_pan_merengue_suizo',
    nombre: 'Merengue Suizo',
    cover: COVER_MERENGUE,
    ingredientes: [
      ing('Azúcar blanca', 100, 'g'),
      ing('Claras de huevo (≈2 und)', 60, 'g'),
      ing('Cremor tártaro / limón', 2, 'g'),
      ing('French vanilla MEC3', 2, 'g'),
    ],
    pasos: [
      'Poner las claras con el azúcar en el bowl de la batidora.',
      'Poner el bowl sobre agua hirviendo en una olla y cocinar, cuidando que el bowl no toque el agua.',
      'Cocinar hasta llegar a 70°C y que no se sientan granos de azúcar.',
      'Agregar el limón y la vainilla y batir hasta montar.',
    ],
  }),
]
